version: "3.9"

services:
  ngrok2:
    image: 127.0.0.1:5000/ngrok:latest
    volumes:
      - /mnt/ngrok2/config/:/app/config/
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role != manager]
        max_replicas_per_node: 1
